# Generated by Django 3.1.6 on 2021-02-17 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('WTG01', 'WTG01'), ('WTG02', 'WTG02'), ('WTG03', 'WTG03'), ('WTG04', 'WTG04'), ('WTG05', 'WTG05'), ('WTG06', 'WTG06'), ('WTG07', 'WTG07'), ('WTG08', 'WTG08'), ('WTG09', 'WTG09'), ('WTG10', 'WTG10'), ('WTG11', 'WTG11'), ('WTG12', 'WTG12'), ('WTG13', 'WTG13'), ('WTG14', 'WTG14'), ('WTG15', 'WTG15'), ('WTG16', 'WTG16'), ('WTG17', 'WTG17')], max_length=20, null=True)),
                ('column_name', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('asset_name', models.CharField(blank=True, choices=[('WTG01', 'WTG01'), ('WTG02', 'WTG02'), ('WTG03', 'WTG03'), ('WTG04', 'WTG04'), ('WTG05', 'WTG05'), ('WTG06', 'WTG06'), ('WTG07', 'WTG07'), ('WTG08', 'WTG08'), ('WTG09', 'WTG09'), ('WTG10', 'WTG10'), ('WTG11', 'WTG11'), ('WTG12', 'WTG12'), ('WTG13', 'WTG13'), ('WTG14', 'WTG14'), ('WTG15', 'WTG15'), ('WTG16', 'WTG16'), ('WTG17', 'WTG17')], max_length=20, null=True)),
                ('value', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='csvs')),
            ],
        ),
        migrations.CreateModel(
            name='Parquet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gzip'])])),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
