# Generated by Django 3.1.6 on 2021-02-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='column',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
